INSERT INTO public.speaker (brand, model, price_inr, category, bluetooth, active, connectivity, description) VALUES
('Edifier', 'MR4', 11990, 'Powered Monitor', false, true, 'RCA/3.5mm', 'Compact powered monitor with warm sound'),
('Edifier', 'MR5BT', 24999, 'Powered Monitor', true, true, 'Bluetooth/RCA/3.5mm', 'Powered monitor with Bluetooth connectivity'),
('Pioneer', 'DM-40D', 20000, 'Powered Monitor', false, true, 'RCA/3.5mm', 'Professional powered monitor with clear midrange'),
('Yamaha', 'HS3', 25000, 'Powered Monitor', false, true, 'XLR/3.5mm', 'Professional studio monitor with accurate response'),
('Edifier', 'R1280DB', 15000, 'Powered Speaker', true, true, 'Bluetooth/RCA/3.5mm/USB', 'Popular powered speaker with subwoofer output'),
('JBL', '104BT', 13000, 'Powered Monitor', true, true, 'Bluetooth/RCA/3.5mm', 'Compact reference monitor with Bluetooth'),
('Presonus', 'Eris 3.5', 12000, 'Powered Monitor', false, true, 'XLR/RCA/3.5mm', 'Budget-friendly studio monitor'),
('Presonus', 'Eris 4.5', 18000, 'Powered Monitor', false, true, 'XLR/RCA/3.5mm', 'Mid-range studio monitor with extended low-end'),
('Audio Technica', 'AT-LP60', 19000, 'Powered Monitor', false, true, 'RCA/3.5mm', 'Turntable-compatible powered monitor'),
('Mackie', 'CR3', 12000, 'Powered Monitor', false, true, 'RCA/3.5mm', 'Compact studio reference monitor'),
('Roland', 'DS-5', 35000, 'Powered Monitor', false, true, 'RCA/3.5mm', 'Digital studio monitor with warm character'),
('Behringer', 'MS16', 8000, 'Powered Speaker', false, true, '3.5mm', 'Budget-friendly compact powered speaker'),
('Kali Audio', 'LP-6', 32000, 'Powered Monitor', false, true, 'XLR/RCA/3.5mm', 'Professional flat-response monitor'),
('Neumann', 'KH80', 90000, 'Powered Monitor', false, true, 'XLR', 'Premium studio reference monitor'),
('Adam Audio', 'A3X', 78000, 'Powered Monitor', false, true, 'XLR/RCA/3.5mm', 'High-end studio monitor'),
('Focal', 'Alpha 50', 70000, 'Powered Monitor', false, true, 'XLR/RCA/3.5mm', 'Professional compact monitor'),
('Genelec', '8030C', 120000, 'Powered Monitor', false, true, 'XLR/RCA', 'Compact nearfield monitor'),
('Sony', 'CAS-1', 55000, 'Powered Speaker', true, true, 'Bluetooth/Aux', 'Portable Bluetooth speaker'),
('Bose', 'Companion 20', 18000, 'Powered Speaker', false, true, 'RCA/3.5mm', 'Desktop speaker system'),
('Harman Kardon', 'SoundSticks IV', 22000, 'Powered Speaker', true, true, 'Bluetooth/3.5mm', 'Designer Bluetooth speaker'),
('Logitech', 'Z333', 6000, 'Powered Speaker', false, true, '3.5mm', 'Compact 2.1 speaker system'),
('Creative', 'T60', 18000, 'Powered Speaker', false, true, 'RCA/3.5mm', 'Retro-styled powered speaker'),
('Audient', 'ASP800', 85000, 'Powered Monitor', false, true, 'XLR/RCA/3.5mm', 'Professional mastering monitor'),
('Dynaudio', 'Lyd-5', 110000, 'Powered Monitor', false, true, 'XLR/RCA/3.5mm', 'Versatile reference monitor'),
('IK Multimedia', 'iLoud MTM', 77000, 'Powered Monitor', false, true, 'XLR/RCA/3.5mm', 'Compact full-range monitor'),
('Elac', 'Debut', 35000, 'Powered Speaker', false, true, 'RCA/3.5mm', 'Quality bookshelf speaker'),
('QSC', 'K8.2', 98000, 'Powered Monitor', false, true, 'XLR/RCA', 'Professional compact reference');